{
  "hash": "87bc23a968d7f7220c52963f1a580540",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Nicole Liddicoat\"\ndate: September 9, 2026\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n\n**In this analysis, I look at total commuters across counties in California, and\nask which communities we measure most and least reliably. Census data helps inform decisions about transporation and infrastructure, so differences in data reliability can affect how communities are represented in those decisions.**\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CA\"        \nmy_variable <- \"B08303_001\"     \n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 06001 Alameda County, California   B08303_001   636741  4570\n2 06003 Alpine County, California    B08303_001      575   146\n3 06005 Amador County, California    B08303_001    13424   667\n4 06007 Butte County, California     B08303_001    80569  1671\n5 06009 Calaveras County, California B08303_001    15129   785\n6 06011 Colusa County, California    B08303_001     8670   606\n```\n\n\n:::\n:::\n\n\n\n\n\n**California has 58 counties, which matches the 58 rows returned.**\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate   moe moe_pct\n   <chr>                          <dbl> <dbl>   <dbl>\n 1 Alpine County, California        575   146   25.4 \n 2 Sierra County, California        921   167   18.1 \n 3 Trinity County, California      3673   529   14.4 \n 4 Modoc County, California        2732   282   10.3 \n 5 Plumas County, California       6381   602    9.43\n 6 Mono County, California         6305   457    7.25\n 7 Colusa County, California       8670   606    6.99\n 8 Mariposa County, California     6240   412    6.60\n 9 Lake County, California        20228  1106    5.47\n10 Lassen County, California       8730   477    5.46\n```\n\n\n:::\n:::\n\n\n**Alpine County, California has the largest margin of error relative to its estimate, making it the least reliable county in the analysis. Its margin of error percentage is 25.4%.**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 8 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    36\n2 Low confidence      5\n3 Moderate           17\n```\n\n\n:::\n:::\n\n\n\nI chose 3% and 8% as the cutoffs because they created a more useful spread of counties across the three reliability categories rather than putting almost every county into one group. The 3% cutoff represents relatively low uncertainty, while 8% identifies estimates with noticeably greater uncertainty. With these cutoffs, 36 counties are high confidence, 17 are moderate, and 5 are low confidence, making it easier to compare counties with different levels of reliability.\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\ncounty_wide %>%\n  select(NAME, myvarE, myvarM, popE) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                            myvarE myvarM    popE\n   <chr>                            <dbl>  <dbl>   <dbl>\n 1 Alameda County, California      636741   4570 1651949\n 2 Alpine County, California          575    146    1695\n 3 Amador County, California        13424    667   41029\n 4 Butte County, California         80569   1671  209470\n 5 Calaveras County, California     15129    785   45995\n 6 Colusa County, California         8670    606   21895\n 7 Contra Costa County, California 448235   4119 1161458\n 8 Del Norte County, California      9273    461   27293\n 9 El Dorado County, California     69437   1669  192299\n10 Fresno County, California       374166   3296 1012152\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 8 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         36       1065959.\n2 Low confidence           5          9713 \n3 Moderate                17         48218 \n```\n\n\n:::\n:::\n\n\n\n\n**The results have a strong relationship between county population and the reliability of the estimates. High-confidence counties have an average population of 1,065,959, compared with only 48,218 for moderate-confidence counties, and 9,713 for low-confidence counties. Smaller communities tend to have greater uncertainty in their estimates because fewer people are represented in the survey sample.**\n\n---\n\n## What this means for policy\n\nThe counties with the least reliable commuter estimates are concentrated among California's smaller, more rural communities. Alpine County has the highest relative margin of error, with an estimated 575 commuters and a margin of error of 146, or 25.4% of its estimate. Sierra County has only 921 estimated commuters and an MOE of 167, giving it an 18.1% margin of error. Trinity County also has substantial uncertainty, with 3,673 commuters and a 14.4% margin of error, while Modoc and Plumas counties have margins of error of 10.3% and 9.43%, respectively. This is very different from a large county like Los Angeles, which has nearly 4 million estimated commuters but a relative margin of error of only 0.31%. The difference reflects how the ACS is based on a sample rather than a complete count of every household. Smaller counties have fewer sampled households representing their communities, so their estimates can be less precise. This creates a potential problem when Census data is used for transportation planning or infrastructure funding. If a state agency treated every county’s commuter estimate as equally certain, it could make decisions based on differences that are partly the result of sampling uncertainty. For example, Alpine County’s estimate of 575 could be substantially higher or lower than its true value. Rural counties such as Alpine, Sierra, and Trinity could therefore have their transportation needs underestimated or overestimated when compared with larger counties whose estimates are much more precise.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}