---
title: "Week 3: ggplot & more MOEs"
description: "..."
date: 2026-09-11
---

## What We Did

NOTES 09/04

Objects, verbs, census.

Step 1 ← filter (counties, moe_pct>10)
Step 2 ← arrange (Step1, desc(moe_pct))
Step 3 ← select (Step2, NAME, moe_pct)

Process made easier by…
Pipe
“and then”
%>%  or  |% (strings functions w/o saving an intermediate file)
E.g. New_data ← counties %>%
                     filter (moe_pct>10) %>%
                     arrange (desc(moe_pct)) %>%
                     select (NAME, moe_pct)

Console

Temporary (code does not get saved anywhere)
Ability to quickly run something 

.R script
Use as history of all of work essentially in blank doc
Code chunk lives inside .qmd


Result ← filter (counties, population>50000) #keep the big ones!
Result: the object that holds the result
←: assignment arrow (aka =)
Filter: Function
Name (verb)
Typically followed by () with arguments inside
Counties: input data
population>50000: arguments 
#: comment; code doesn’t run

Packages
install.packages(“dplyr”) → do ONCE (like buying a book)
Library(dplyr) → took the book off the shelf
Every time you want to use functions that belong to dplyr

What is dplyr??
Package for working with tables 
Aka dataframe
Every row in dataframe is known as an observation 
Column are known as variables
tibble (nicer, prints prettier)
tibble → verb → tibble

Things to know
filter ( ) → picks rows
select ( ) → picks columns
mutate ( ) → add a new computed column
New ← mutate (counties, income2  )
arrange ( ) → change order of rows
Ascending or descending order, e.g.
group_by ( ) + summarize ( ) → where many rows become few


Census
Decennial census
10 Q’s for everyone living in this country legally or illegally (theoretically)
Some people would receive longform (sample pop.)

American Community Survey (ACS)
2005 ish born 
3% of households surveyed as a sample pop.
From that sample, we come up with an estimate for the pop.
Introduced large MOE
Types
1 yr ACS
Places > 65,000. Most current
3 yr ACS 
DEAD
5 yr ACS
Census block group, census tract
Takes a 5-yr average
Estimate +- margin of error 
Supplemented with the yearly ACS sampling in more places (average of all of those years becomes the 5-yr ACS)

Base table
B^19013_001E
Table #, line #, E=estimate, M=MOE
Load_variables ( )

Hierarchy 
State
County
Tract (“nieghborhood”) 
Roughly 5,000 - 8,000 people per tract
Boundaries change all the time 
Block groups
High MOE 
Block
Decennial only

GEOID 
Extension of FIPS code place identifier
First 2 #: State
Next 3 #: county
Next #: tract (11 digits)
Next # block group (last; 12th)

data ← get_acs ( geography = “county”, 
                           variables = c(“B19013_001”, 
                                                “B01003_001”),
                           state = “PA”,
                           year = 2023,
                           survey = “acs5” )
		   output = “wide”
c=caconitate (aka make a list)

TIDY 
Long format
GEOID | NAME | Variable | Estimate | MOE
Good for mapping
Typically want data in WIDE format
GEOID | NAME | B1901301 | Variable 
Good for operations, verbs, etc

...

